baseURL = 'https://mowmark.github.io/'
locale = 'zh-cn'
title = 'MowMark 的个人博客'
theme = 'terminal'

paginate = 8

[author]
  name = "MowMark"

[params]
  subtitle = "记录 Linux 与 SLAM 的学习日志."
  contentTypeName = 'posts'
  showMenuItems = 5
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = false
  autoCover = true
  showLastUpdated = true
  Toc = true
  showCodeCopyButtons = true
  showReadingTime = true

[language]
  [languages.zh]
    languageName = "简体中文"
    title = "Terminal"
    
    [languages.zh.params]
      subtitle = "A simple, retro theme for Hugo"
      owner = ""
      keywords = ""
      copyright = ""
      menuMore = "更多内容"
      readMore = "查看"
      readOtherPosts = "阅读其他文章"
      missingContentMessage = "找不到文章"
      missingBackButtonLabel = "回到主页"
      minuteReadingTime = "最少阅读时间"

    [languages.zh.params.logo]
        logoText = "MowMark's Blog"
        logoHomeLink = "/"

      [languages.zh.menu]
        [[languages.zh.menu.main]]
          identifier = "about"
          name = "关于"
          url = "/about"
          weight = 10
        [[languages.zh.menu.main]]
          identifier = "posts"
          name = "目录"
          url = "/posts/"
          weight = 20
        [[languages.zh.menu.main]]
          identifier = "linux"
          name = "Linux折腾实况"
          url = "/categories/linux"
          weight = 30
        [[languages.zh.menu.main]]
          identifier = "slam"
          name = "SLAM学习实况"
          url = "/categories/slam"
          weight = 40
        [[languages.zh.menu.main]]
          identifier = "others"
          name = "其他"
          url = "/categories/others/"
          weight = 50
